config/routes.rb
Rails.application.routes.draw do
  resources :contacts, path: '/'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :phones, dependent: :destroy
  has_many :emails, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name,  presence: true

  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :emails, allow_destroy: true
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :contact
  validates :contact, presence: true

  validates :address, presence: true
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
  validates :contact, presence: true

  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: 'Contact was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def readonly
       %w[index show].include?(action_name) ? true : false
    end
    helper_method :readonly

    # Only allow a trusted parameter "white list" through.
    def contact_params
      params.require(:contact).permit(:first_name,
                                      :last_name,
                                      :street_1,
                                      :street_2,
                                      :city,
                                      :subnational_jurisdiction,
                                      :postal_code,
                                      :country,
                                      phones_attributes: [:id, :number, :label, :_destroy],
                                      emails_attributes: [:id, :address, :label, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association, cssClass, title)
    # Particularly helpful: http://stackoverflow.com/questions/23777751/link-to-add-fields-unobtrusive-javascript-rails-4
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to name, "javascript:void(0)", onclick: "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", class: cssClass, title: title
  end
end

app/views/contacts/_email_fields.html.slim
.row
  .expandable_fields
    .three.columns
      = f.label :address, :address
      = f.text_field :address, disabled: readonly
    .three.columns
      = f.label :label, :label
      = f.text_field :label, disabled: readonly
    - unless readonly
      .three.columns.link-container
        = f.hidden_field :_destroy
        = link_to 'remove', 'javascript:void(0);', class: 'remove_link'

app/views/contacts/_form.html.slim
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      ul
        - @contact.errors.full_messages.each do |message|
          li = message

  .row
    .three.columns
      = f.label :first_name
      = f.text_field :first_name, disabled: readonly
    .three.columns
      = f.label :last_name
      = f.text_field :last_name, disabled: readonly
  .row
    = f.label :street_1, 'Street Address'
    = f.text_field :street_1, disabled: readonly
    .field
    = f.text_field :street_2, disabled: readonly
  .row
    .three.columns
      = f.label :city
      = f.text_field :city, disabled: readonly
    .three.columns
      = f.label :subnational_jurisdiction, 'State/Province'
      = f.text_field :subnational_jurisdiction, disabled: readonly
    .three.columns
      = f.label :postal_code
      = f.text_field :postal_code, disabled: readonly
  .row
    .three.columns
      = f.label :country
      = f.text_field :country, disabled: readonly

  h3 Phone Numbers
  = f.fields_for :phones do |builder|
    == render 'phone_fields', f: builder
  - unless readonly
    = link_to_add_fields 'Add Phone', f, :phones, '', 'Add a new Phone'


  h3 Email Addresses
  = f.fields_for :emails do |builder|
    == render 'email_fields', f: builder
  - unless readonly
    = link_to_add_fields 'Add Email', f, :emails, '', 'Add a new Email'

  - unless readonly
    .actions = f.submit class: 'button-primary'

app/views/contacts/_phone_fields.html.slim
.row
  .expandable_fields
    .three.columns
      = f.label :number, :number
      = f.text_field :number, disabled: readonly
    .three.columns
      = f.label :label, :label
      = f.text_field :label, disabled: readonly
    - unless readonly
      .three.columns.link-container
        = f.hidden_field :_destroy
        = link_to 'remove', 'javascript:void(0);', class: 'remove_link'

app/views/contacts/edit.html.slim
h2 Edit Contact Details

== render 'form'

= link_to 'Show', @contact, class: 'button'
= link_to 'Back', contacts_path, class: 'button'

app/views/contacts/index.html.slim
table
  thead
    tr
      th First name
      th Last name
      th Address
      th City
      th State/Prov
      th Postal Code
      th Country
      th
      th
      th

  tbody
    - @contacts.each do |contact|
      tr.clickable-row[data-href="#{contact_path(contact.id)}"]
        td
          div = contact.first_name
        td
          div = contact.last_name
        td
          - street = contact.street_1
          - street += ", #{contact.street_2}" unless contact.street_2.blank?
          div = street
        td
          .small = contact.city
        td
          .small = contact.subnational_jurisdiction
        td
          .small = contact.postal_code
        td
          .small = contact.country
        td
          div = link_to 'Edit', edit_contact_path(contact), class: 'button'
        td
          div = link_to 'Destroy', contact, data:   { confirm: 'Are you sure?' },
                                            method: :delete,
                                            class:  'button'

br

= link_to 'New Contact', new_contact_path, class: 'button button-primary'

app/views/contacts/new.html.slim
h2 New contact

== render 'form'

= link_to 'Back', contacts_path, class: 'button'

app/views/contacts/show.html.slim
h2 Contact Details


p#notice = notice

== render 'form'

= link_to 'Edit', edit_contact_path(@contact), class: 'button'
= link_to 'Back', contacts_path, class: 'button'

app/views/layouts/application.html.slim
doctype html
html
  head
    title cloudcontacts
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  body
    .container
      .row
        header
          h1
            a[href="/"] cloudcontacts
      .row
        = yield